# Generated by Django 2.2.28 on 2022-11-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_addressohcfxmhpyt'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressohcfxmhpyt',
            name='ca',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
